### ISSUE TITLE
Minimal Python version

### ISSUE THREAD

**Issue by cernyd** [IamEld3st/youtube_dash_dl#11]
I am wondering if Python 3.7 isn't too new to be the default, many systems are still shipping with version 3.6.9 by default.

**Comment by IamEld3st** [comment]
That is true... the usage of Python 3.7 here is due to format strings iirc... personally I got used to them when writing python so that is why it is currently sitting at 3.7.
But the fact is a lot of people and systems still have 3.6.x so it would be wise to rewrite format strings and any other code that is incompatible... also checking of dependencies if they support 3.6 is a good idea.

**Comment by IamEld3st** [comment]
I tested the program on 3.6 and it ran without any serious problems... the only thing I found is the fact that download bar is freezing more, but after giving it time it always updated.
Keeping open for a week and if no other problems show will close.
