### ISSUE TITLE
android package doesnt want to install

### ISSUE THREAD

**Issue by tojestzart** [IamEld3st/youtube_dash_dl#24]
[text here](https://pastebin.com/fSpQXuag)

**Comment by tojestzart** [comment]
@jackorp

```$ termux-info
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=23550
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.30.2
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Sep 15 06:16:04 CDT 2022 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g31(w)
~ $```

`$ pip --version
pip 22.3 from /data/data/com.termux/files/usr/lib/python3.10/site-packages/pip (python 3.10)
~ $`

**Comment by jackorp** [comment]
the problem is that you are missing development C libraries for the library this project uses.

From the log:
```
      Package libavdevice was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libavdevice.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libavdevice' found
```
This means that it could not find file libavdevice.pc to be able to install the C extension that uses it.
Other paragraphs list the same. You'll have to figure out how to get these C dependencies into the correct locations.

You are missing following libraries: `libavformat` `libavcodec` `libavdevice` `libavutil` `libavfilter` `libswscale` `libswresample`

**Comment by tojestzart** [comment]
@jackorp 
Problem is all or part of them are related to ffmpeg, dont know how to install separetly liblaries. For x64 pip install youtube-dash- dl is enough it has some procedure for it.

**Comment by tojestzart** [comment]
[paste](https://pastebin.com/qsHNanq0) i give up
